namespace: citus

image:
    citus: citusdata/citus:13.0
    postgres: postgres:18.3
    locker: postgres:18.3

postgres:
    user: postgres
    password: "111"
    db: postgres
    port: 5432
    config:
        walLevel: logical
        maxReplicationSlots: 10
        maxWalSenders: 10
        maxLogicalReplicationWorkers: 10
        maxWorkerProcesses: 20

masters:
    - name: master-1
      serviceName: master-1
      storageClassName: master-1-storage
      storageSize: 10Gi
      mountPath: /var/lib/postgresql
      replicas: 1

    - name: master-2
      serviceName: master-2
      storageClassName: master-2-storage
      storageSize: 10Gi
      mountPath: /var/lib/postgresql
      replicas: 1

    - name: master-3
      serviceName: master-3
      storageClassName: master-3-storage
      storageSize: 10Gi
      mountPath: /var/lib/postgresql
      replicas: 1

coordinators:
    - name: coordinator-1
      serviceName: coordinator-1
      storageClassName: coordinator-1-storage
      storageSize: 10Gi
      mountPath: /var/lib/postgresql
      replicas: 1

    - name: coordinator-2
      serviceName: coordinator-2
      storageClassName: coordinator-2-storage
      storageSize: 10Gi
      mountPath: /var/lib/postgresql
      replicas: 1

    - name: coordinator-3
      serviceName: coordinator-3
      storageClassName: coordinator-3-storage
      storageSize: 10Gi
      mountPath: /var/lib/postgresql
      replicas: 1

workers:
    - name: worker-1
      serviceName: worker-1-headless
      headless: true
      storageClassName: worker-1-storage
      storageSize: 10Gi
      mountPath: /var/lib/postgresql
      replicas: 3
      coordinatorName: coordinator-1

    - name: worker-2
      serviceName: worker-2-headless
      headless: true
      storageClassName: worker-2-storage
      storageSize: 10Gi
      mountPath: /var/lib/postgresql
      replicas: 3
      coordinatorName: coordinator-2

    - name: worker-3
      serviceName: worker-3-headless
      headless: true
      storageClassName: worker-3-storage
      storageSize: 10Gi
      mountPath: /var/lib/postgresql
      replicas: 3
      coordinatorName: coordinator-3

locker:
    enabled: true
    name: pg-locker
    serviceName: pg-locker
    storageClassName: pg-locker-storage
    storageSize: 5Gi
    mountPath: /var/lib/postgresql
    replicas: 1