{{- if .Values.locker.enabled }}
---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.locker.serviceName }}
    namespace: {{ .Values.namespace }}
spec:
    selector:
        app: {{ .Values.locker.name }}
    ports:
        - port: {{ .Values.postgres.port }}
          targetPort: {{ .Values.postgres.port }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ .Values.locker.name }}
    namespace: {{ .Values.namespace }}
spec:
    serviceName: {{ .Values.locker.serviceName }}
    replicas: {{ .Values.locker.replicas }}
    selector:
        matchLabels:
            app: {{ .Values.locker.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.locker.name }}
        spec:
            containers:
                - name: postgres
                  image: {{ .Values.image.locker }}
                  command:
                      - docker-entrypoint.sh
                      - postgres
                      - -c
                      - wal_level={{ .Values.postgres.config.walLevel }}
                      - -c
                      - max_replication_slots={{ .Values.postgres.config.maxReplicationSlots }}
                      - -c
                      - max_wal_senders={{ .Values.postgres.config.maxWalSenders }}
                      - -c
                      - max_logical_replication_workers={{ .Values.postgres.config.maxLogicalReplicationWorkers }}
                      - -c
                      - max_worker_processes={{ .Values.postgres.config.maxWorkerProcesses }}
                  ports:
                      - containerPort: {{ .Values.postgres.port }}
                  env:
                      - name: POSTGRES_DB
                        value: "{{ .Values.postgres.db }}"
                      - name: POSTGRES_USER
                        value: "{{ .Values.postgres.user }}"
                      - name: POSTGRES_PASSWORD
                        value: "{{ .Values.postgres.password }}"
                  volumeMounts:
                      - name: data
                        mountPath: {{ .Values.locker.mountPath }}
    volumeClaimTemplates:
        - metadata:
              name: data
          spec:
              accessModes:
                  - ReadWriteOnce
              storageClassName: {{ .Values.locker.storageClassName }}
              resources:
                  requests:
                      storage: {{ .Values.locker.storageSize }}
{{- end }}