{{- range .Values.masters }}
---
apiVersion: v1
kind: Service
metadata:
    name: {{ .serviceName }}
    namespace: {{ $.Values.namespace }}
spec:
    selector:
        app: {{ .name }}
    ports:
        - port: {{ $.Values.postgres.port }}
          targetPort: {{ $.Values.postgres.port }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ .name }}
    namespace: {{ $.Values.namespace }}
spec:
    serviceName: {{ .serviceName }}
    replicas: {{ .replicas }}
    selector:
        matchLabels:
            app: {{ .name }}
    template:
        metadata:
            labels:
                app: {{ .name }}
        spec:
            containers:
                - name: {{ .name }}
                  image: {{ $.Values.image.postgres }}
                  command:
                      - docker-entrypoint.sh
                      - postgres
                      - -c
                      - wal_level={{ $.Values.postgres.config.walLevel }}
                      - -c
                      - max_replication_slots={{ $.Values.postgres.config.maxReplicationSlots }}
                      - -c
                      - max_wal_senders={{ $.Values.postgres.config.maxWalSenders }}
                      - -c
                      - max_logical_replication_workers={{ $.Values.postgres.config.maxLogicalReplicationWorkers }}
                      - -c
                      - max_worker_processes={{ $.Values.postgres.config.maxWorkerProcesses }}
                  ports:
                      - containerPort: {{ $.Values.postgres.port }}
                  env:
                      - name: POSTGRES_DB
                        value: "{{ $.Values.postgres.db }}"
                      - name: POSTGRES_USER
                        value: "{{ $.Values.postgres.user }}"
                      - name: POSTGRES_PASSWORD
                        value: "{{ $.Values.postgres.password }}"
                      - name: PGUSER
                        value: "{{ $.Values.postgres.user }}"
                      - name: PGPASSWORD
                        value: "{{ $.Values.postgres.password }}"
                  volumeMounts:
                      - name: data
                        mountPath: {{ .mountPath }}
    volumeClaimTemplates:
        - metadata:
              name: data
          spec:
              accessModes:
                  - ReadWriteOnce
              storageClassName: {{ .storageClassName }}
              resources:
                  requests:
                      storage: {{ .storageSize }}
{{- end }}